sudo: required
services:
  - docker

before_install:
  - docker build -t conorburke/fantasy-test ./etl

script:
  - docker run conorburke/fantasy-test go test

after_success:
  - docker build -t conorburke/fantasy-api ./api
  - docker build -t conorburke/fantasy-etl ./etl
  - docker build -t conorburke/fantasy-database ./database
  - docker build -t conorburke/fantasy-frontend ./frontend
  - docker build -t conorburke/fantasy-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push conorburke/fantasy-api
  - docker push conorburke/fantasy-etl
  - docker push conorburke/fantasy-database
  - docker push conorburke/fantasy-frontend
  - docker push conorburke/fantasy-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: fantasy
  env: Fantasy-env
  bucket_name: fantasy-zipped
  bucket_path: fantasy-files
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY