version: '3'
services:
  api:
    build: ./api
    environment:
      - PORT=7000
      - "FANTASY_DB_PASS=${FANTASY_DB_PASS}"
    ports:
      - '7000:7000'
    depends_on:
      - database
    # restart: always
    links:
      - database
  etl:
    build: ./etl
    environment:
      - "FANTASY_DB_PASS=${FANTASY_DB_PASS}"
    ports:
      - '9000:9000' 
    depends_on:
      - database
    # restart: always
    links:
      - database
  database:
    build: ./database  
    ports:
      - '5432:5432' 
    command: postgres -c 'max_connections=10000'
    environment:
      - "FANTASY_DB_PASS=${FANTASY_DB_PASS}"
  frontend:
    build:
      dockerfile: Dockerfile.dev 
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./frontend:/frontend
  nginx:
    restart: always
    depends_on:
      - api
    build: ./nginx
    ports:
      - '8080:80'