version: '3'
services:
  api:
    build: ./api
    environment:
      - PORT=7000
    ports:
      - '7000:7000'
    depends_on:
      - database
      - common
    # restart: always
    links:
      - database
  etl:
    build: ./etl
    ports:
      - '9000:9000' 
    depends_on:
      - database
      - common
    # restart: always
    links:
      - database
  common:
    build: ./common
  database:
    build: ./database  
    ports:
      - '5432:5432' 
    command: postgres -c 'max_connections=10000'