version: '3'
services:
  etl:
    build: ./etl
    ports:
      - '9000:9000' 
    depends_on:
      - database
    # restart: always
    links:
      - database
  database:
    build: ./database  
    ports:
      - '5432:5432' 
    command: postgres -c 'max_connections=10000'